### ISSUE TITLE
Create a Roadmap

### ISSUE THREAD

**Issue by lp55** [benleb/surepy#220]
Hi,

@benleb has invited me to collaborate on the surepy & sureha repos. So I thought that one of the first things that should be done is a roadmap. Here are the itens I though about:

- Add Tests (this would make it easier to verify when APIs change/break the current code
- Fix standing bugs
- Improve code documentation
- Improve README
- Merge the Felaqua code I did in my repos (added drinking consumption habits for the pets and sensors for sureha)

Any other ideas?
And who else is willing to help?
I only have a Felaqua, so there's a limit in what I can help regarding some bugs/features with my current access.

**Comment by Zhephyr54** [comment]
Hi,
On the HA integration, It could be nice to support custom locations when having more than 1 flap. Not sure how hard it would be to implement but it could work like this:
- On initial setup of the integration, if detecting more than 1 flap, add the possibility to configure a mapping for each flap in/out with the Location enums (Inside, Outside) + HA areas (or simple string if its too complicated), so you could map it this way for example :
    - Hallway flap In:  Inside
    - Hallway flap Out: garage
    - Garage flap In: garage
    - Garage flap out: Outside
- Change the cat binary sensor to a select

What do you think?

**Comment by FirstRulez** [comment]
> Hi, On the HA integration, It could be nice to support custom locations when having more than 1 flap. Not sure how hard it would be to implement but it could work like this:
> 
> * On initial setup of the integration, if detecting more than 1 flap, add the possibility to configure a mapping for each flap in/out with the Location enums (Inside, Outside) + HA areas (or simple string if its too complicated), so you could map it this way for example :
>   
>   * Hallway flap In:  Inside
>   * Hallway flap Out: garage
>   * Garage flap In: garage
>   * Garage flap out: Outside
> * Change the cat binary sensor to a select
> 
> What do you think?

This is something I'd really appreciate - we have a setup like this with two flaps which Sure have no interest in supporting from the feedback I've had.

**Comment by lp55** [comment]
That's an interesting suggestion. Would any of you be willing to help with data or code for that? I don't have flaps, so I can't test that with my user data.

**Comment by Zhephyr54** [comment]
Sure, I would be glad to help.
I got the logic implemented in node red for now:
When any of the binary sensors state for my cats change, I am getting the pets info from the `/api/pet?with=position`
 endpoint:
```json
// Ids changed
{
    "data": [
        {
            "id": 1,
            "name": "Cat 1",
            "gender": 1,
            ..., // omitted
            "status": {
                "activity": {
                    "id": 42,
                    "pet_id": 1,
                    "tag_id": 11,
                    "device_id": 116,
                    "where": 1,
                    "since": "2025-02-25T06:02:53+00:00"
                },
                "feeding": {
                    ... // omitted
                }
            },
            "position": {
                "id": 42,
                "pet_id": 1,
                "tag_id": 11,
                "device_id": 116,
                "where": 1,
                "since": "2025-02-25T06:02:53+00:00"
            }
        },
        ... // other pet, omitted
    ],
    "meta": {
        "page": 1,
        "page_size": 1000,
        "count": 2,
        "total_pages": 1
    }
}
```
Then, knowing which device id is corresponding to which flap, I am just mapping the `position` (`activity` seems to also contains the same info but I guess it might contain other info depending on the last activity of the cat (feeding, drinking...)) `device_id` + `where` (inside/outside) to the matching location string and set the pet input_select.

**Comment by Zhephyr54** [comment]
Just to let you know, I implemented this feature in the core integration, but have not yet submitted a PR as I would need a change in the HA core architecture to correctly handle the new config flow step form translations.
[Here is the proposal](https://github.com/home-assistant/architecture/discussions/1214) if anyone wants to help by upvoting it.

Here is what it looks like (I have 2 flaps):
- Conflig flow:
![Image](https://github.com/user-attachments/assets/438c7a4c-8037-4f7f-af83-118b8ac586a2)
![Image](https://github.com/user-attachments/assets/dbbfc3ee-2b81-4547-958d-4c9c31ac63c9)
![Image](https://github.com/user-attachments/assets/e5130fc8-9238-49d1-a694-d172ceb42f3f)

- New select entity per cat:
![Image](https://github.com/user-attachments/assets/87c8f4bf-a267-45a2-905b-698e19f22381)

**Comment by benleb** [comment]
@lp55 if you need anything, feel free to contact me (dont know how to contact you 😅).

@Zhephyr54 nice work! :D 

About the "tests" and "docs" in the roadmap, I think that can do an AI for us 👍 Will try it at the weekend :D And guess I will also be able to be more active again in `future` probably :) (If its urgent or so, please try to contact me directly, not via github :D)

**Comment by Daneish** [comment]
Hi Ip55, thanks for jumping in to work on the repos! I have two Feeder bowls. I’m not a developer, but would be happy to help with testing, or interacting with the API to provide information on the Feeders.

**Comment by FredrikM97** [comment]
A contribution file would be nice

**Comment by Zhephyr54** [comment]
@benleb I just submitted a [PR](https://github.com/home-assistant/core/pull/145095) to add the pet location select entity feature to the HA core integration 😄

**Comment by FredrikM97** [comment]
After looking a bit at the repository I feel that a lot of functionality is bundled together and a bit hard coded. It kind of works but difficult to test and update. I started working on a new implementation that hopefully can use the v2 api (noticed that the api is still lacking)
Feel free to take inspiration if you want for this project. https://github.com/FredrikM97/py-surepetcare

**Comment by lp55** [comment]
> After looking a bit at the repository I feel that a lot of functionality is bundled together and a bit hard coded. It kind of works but difficult to test and update. I started working on a new implementation that hopefully can use the v2 api (noticed that the api is still lacking) Feel free to take inspiration if you want for this project. https://github.com/FredrikM97/surepy

HI, I felt the same when I took a closer look at the code. There's also a lot of unused code. I also think [sureha](https://github.com/benleb/sureha) has some similar issues. That's why I asked if people were using surepy outside sureha/home assistant [here](https://github.com/benleb/surepy/issues/221). My idea was to sort redo it. Here's what I though would be a good structure:

REST API calls
|->remove unused calls
|->api tests that validate that the expected response is still returned (so if SurePet changes something in the API, it's quickly caught)
|->mock tests
|->converts json to proper python data structure (using enums instead of numbers, etc, but keeping it very close to the JSON)

HA part
|-> structures pooling, stores data to reduce data requests
|-> converts api calls data structure to ha data structure
|-> implement tests

I haven't taken a detailed look at @FredrikM97 code, but it seems like you had a similar idea.
Life happened in this meanwhile and I haven't had time to work on this code yet. But hopefully in the next week I'll have more time to do so.
One thing I remember from the original surepy/sureha is that appears to have some weird edge cases / api / ha issues that it had to workaround it. It seems to be more on the pet flap code. That's a point of attention.

**Comment by lp55** [comment]
> After looking a bit at the repository I feel that a lot of functionality is bundled together and a bit hard coded. It kind of works but difficult to test and update. I started working on a new implementation that hopefully can use the v2 api (noticed that the api is still lacking) Feel free to take inspiration if you want for this project. https://github.com/FredrikM97/surepy

@FredrikM97 I suggest that you rename you repo to something like surepy2 or sureapi or whatever so it's not confused as a simple fork. Your code can't be used by sureha directly, correct?

**Comment by FredrikM97** [comment]
> ->remove unused calls |->api tests that validate that the expected response is still returned (so if SurePet changes something in the API, it's quickly caught) |->mock tests |->converts json to proper python data structure (using enums instead of numbers, etc, but keeping it very close to the JSON)
> 
> HA part |-> structures pooling, stores data to reduce data requests |-> converts api calls data structure to ha data structure |-> implement tests

This is a good idea. It might be worth creating a surepyv2 or similar module within this library. I started refactoring parts of the original surepy code, but the lack of tests and the tight coupling between devices (especially the flap), client, and authentication made it very challenging to make changes without breaking existing functionality.

Additionally, I’m concerned that the client currently stores the username and password in plain text, which is not ideal from a security perspective.


> > After looking a bit at the repository I feel that a lot of functionality is bundled together and a bit hard coded. It kind of works but difficult to test and update. I started working on a new implementation that hopefully can use the v2 api (noticed that the api is still lacking) Feel free to take inspiration if you want for this project. https://github.com/FredrikM97/surepy
> 
> [@FredrikM97](https://github.com/FredrikM97) I suggest that you rename you repo to something like surepy2 or sureapi or whatever so it's not confused as a simple fork. Your code can't be used by sureha directly, correct?

That’s correct. My repository will break the current sureha implementation, and I’m still missing support for several devices and POST requests. However, the existing sureha implementation is already broken for Feeder Connect and I feel it have a complex structure for adding new devices. I hope to eventually create a new sureha integration that is built around actual devices, rather than mapping sensors as devices (which is how the feeder is currently handled).

I hope I can create a guide in the near future to guide users to create pull requests/mock data so I can implement support for  more device.

**Comment by lp55** [comment]
Hi. I created a [v2 branch](https://github.com/benleb/surepy/tree/v2) here. We can work on on this massive refactor in this branch until still stable and functional enough to replace the main branch.

Can you open a PR to this new branch with your code, so we can working on it together here?

As for the user/password in plain text, unless you integrate it with some type of wallet / password manager, there's isn't really a good solution. Encryption with a key on an open source project, where the key in well known isn't really useful. Honestly I think that would be more of an issue in sureha then surepy. surepy should request the user/password when it's instantiated. How that password is stored is not the lib's problem. Unless you have an idea in mind for this?

**Comment by FredrikM97** [comment]
I believe the email and password should never be stored, as the current implementation does. Only the token should be retained. If storing the email and password is necessary, it should be the responsibility of the Home Assistant integration. I see no reason why the surepy library itself should need to retain them.

**Comment by lp55** [comment]
That I agree with the surepy not storing the password. I was thinking more on the sureha storing password part. But one thing, how long a token is valid for? The timestamp of the token should return with the api call that produces a token based on user/password so the application that user surepy knows when it has to request a new token

**Comment by FredrikM97** [comment]
> That I agree with the surepy not storing the password. I was thinking more on the sureha storing password part. But one thing, how long a token is valid for? The timestamp of the token should return with the api call that produces a token based on user/password so the application that user surepy knows when it has to request a new token

No clue how long it last. I will set up a custom component and test it. I would assume indefinetly like the surepetcare app. One way is for ha to catch Auth errors so one way or another the user will know.

**Comment by FredrikM97** [comment]
@Zhephyr54 if you have a flap could you help me extract data for mock testing? I have a contribution section to download data from the api at https://github.com/FredrikM97/py-surepetcare/tree/main/contribute.

**Comment by Zhephyr54** [comment]
> [@Zhephyr54](https://github.com/Zhephyr54) if you have a flap could you help me extract data for mock testing? I have a contribution section to download data from the api at https://github.com/FredrikM97/py-surepetcare/tree/main/contribute.

I am getting the following error: AttributeError: 'SurePetcareClient' object has no attribute 'get_households'

**Comment by FredrikM97** [comment]
> > [@Zhephyr54](https://github.com/Zhephyr54) if you have a flap could you help me extract data for mock testing? I have a contribution section to download data from the api at https://github.com/FredrikM97/py-surepetcare/tree/main/contribute.
> 
> I am getting the following error: AttributeError: 'SurePetcareClient' object has no attribute 'get_households'

@Zhephyr54 Sorry about that. Did a rework a while back to separate concerns and forgot to update the contribution. It is now corrected and should work.

**Comment by cdce8p** [comment]
Hello everyone! I'm currently working on Python 3.14 support for Home Assistant. It seems `surepy` has a too restrictive pin on `rich` which will now emit warnings already fixed in newer releases. I created #226 to update the dependencies. Would be awesome if someone is able to take a look and ideally do a new release afterwards. So that `surepy` can be bumped in Home Assistant and the issue be resolved.
